name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Baixar dataset MovieLens
        run: |
          curl -L -o ml.zip https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
          unzip -q ml.zip -d data
          ls data/ml-latest-small

      - name: Rodar testes
        run: python -m pytest -q